### ISSUE TITLE
报错:ActionFailed(status='failed', retcode=1200, data=None, message='音乐签名地址未配置', wording='音乐签名地址未配置', echo='14')

### ISSUE THREAD

**Issue by tamakyi** [CCYellowStar2/nonebot_plugin_asmr#2]
![Screenshot_20240626_023439](https://github.com/CCYellowStar2/nonebot-plugin-asmr/assets/25850853/c86972be-54ab-4db9-bef0-108bd9f77d9c)
如图所示，最后一步发送序号的时候报错:ActionFailed(status='failed', retcode=1200, data=None, message='音乐签名地址未配置', wording='音乐签名地址未配置', echo='14')

**Comment by CCYellowStar2** [comment]
什么框架

**Comment by tamakyi** [comment]
> 什么框架

llonebot

**Comment by TsukimoriRin** [comment]
同llonebot 框架报错
06-27 17:37:57 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_asmr, lineno=38) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever    self._run_once()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot_plugin_asmr\__init__.py", line 184, in _play2
    await play.send(m)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\****\Desktop\bot\******\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='消息体无法解析', wording='消息体无法解析', echo='12')

**Comment by tamakyi** [comment]
搞懂问题所在了，我的我的
