### ISSUE TITLE
这是咋回事

### ISSUE THREAD

**Issue by YRRLYB** [CCYellowStar2/nonebot_plugin_asmr#3]
06-30 11:41:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_asmr, lineno=40)
06-30 11:41:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_asmr, lineno=40) running complete
06-30 11:41:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_asmr, lineno=40) failed.
Traceback (most recent call last):
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 494, in finish_recv
    return ov.getresult()
OSError: [WinError 64] 指定的网络名不再可用。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1133, in _create_connection_transport
    await waiter
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 286, in _loop_reading
    length = fut.result()
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 498, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 64] 指定的网络名不再可用。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\26956\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\nonebot_plugin_asmr\__init__.py", line 65, in _search
    res = await session.get(f"https://api.asmr-200.com/api/search/{keyword}?order=dl_count&sort=desc&page={y}&subtitle=0&includeTranslationWorks=true", headers=headers, timeout=10)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\bot\llonebot\nonebot\budingbot\.venv\lib\site-packages\aiohttp\connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.asmr-200.com:443 ssl:default [指定的网络名不再可用。]

**Comment by CCYellowStar2** [comment]
可能网络环境问题

**Comment by YRRLYB** [comment]
是得挂梯子才可以吗

**Comment by CCYellowStar2** [comment]
> 是得挂梯子才可以吗
> 

不需要挂

**Comment by YRRLYB** [comment]
佬，有什么解决办法吗

**Comment by laiyoi** [comment]
```
07-13 16:14:35 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_asmr, lineno=40) failed.
Traceback (most recent call last):
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
    hosts = await self._resolve_host(host, port, traces=traces)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
    return await asyncio.shield(resolved_host_task)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 901, in getaddrinfo
    return await self.run_in_executor(
  File "E:\anaconda\envs\nb\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\anaconda\envs\nb\Lib\socket.py", line 964, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\nb\test\bot.py", line 19, in <module>
    nonebot.run()
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\anaconda\envs\nb\Lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "E:\anaconda\envs\nb\Lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "E:\anaconda\envs\nb\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "E:\anaconda\envs\nb\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "E:\anaconda\envs\nb\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "E:\anaconda\envs\nb\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\anaconda\envs\nb\Lib\site-packages\nonebot_plugin_asmr\__init__.py", line 65, in _search
    res = await session.get(f"https://api.asmr-200.com/api/search/{keyword}?order=dl_count&sort=desc&page={y}&subtitle=0&includeTranslationWorks=true", headers=headers, timeout=10)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.asmr-200.com:443 ssl:default [getaddrinfo failed]
```

**Comment by CCYellowStar2** [comment]
> ```
> 07-13 16:14:35 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_asmr, lineno=40) failed.
> Traceback (most recent call last):
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 1203, in _create_direct_connection
>     hosts = await self._resolve_host(host, port, traces=traces)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 880, in _resolve_host
>     return await asyncio.shield(resolved_host_task)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 917, in _resolve_host_with_throttle
>     addrs = await self._resolver.resolve(host, port, family=self._family)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\resolver.py", line 33, in resolve
>     infos = await self._loop.getaddrinfo(
>   File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 901, in getaddrinfo
>     return await self.run_in_executor(
>   File "E:\anaconda\envs\nb\Lib\concurrent\futures\thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "E:\anaconda\envs\nb\Lib\socket.py", line 964, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 11004] getaddrinfo failed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "E:\nb\test\bot.py", line 19, in <module>
>     nonebot.run()
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\__init__.py", line 335, in run
>     get_driver().run(*args, **kwargs)
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
>     uvicorn.run(
>   File "E:\anaconda\envs\nb\Lib\site-packages\uvicorn\main.py", line 577, in run
>     server.run()
>   File "E:\anaconda\envs\nb\Lib\site-packages\uvicorn\server.py", line 65, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "E:\anaconda\envs\nb\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>   File "E:\anaconda\envs\nb\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>   File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 674, in run_until_complete
>     self.run_forever()
>   File "E:\anaconda\envs\nb\Lib\asyncio\windows_events.py", line 322, in run_forever
>     super().run_forever()
>   File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 641, in run_forever
>     self._run_once()
>   File "E:\anaconda\envs\nb\Lib\asyncio\base_events.py", line 1987, in _run_once
>     handle._run()
>   File "E:\anaconda\envs\nb\Lib\asyncio\events.py", line 88, in _run
>     self._context.run(self._callback, *self._args)
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
>     await _run_matcher(
> > File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\message.py", line 428, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
>     await handler(
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "E:\anaconda\envs\nb\Lib\site-packages\nonebot_plugin_asmr\__init__.py", line 65, in _search
>     res = await session.get(f"https://api.asmr-200.com/api/search/{keyword}?order=dl_count&sort=desc&page={y}&subtitle=0&includeTranslationWorks=true", headers=headers, timeout=10)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\client.py", line 581, in _request
>     conn = await self._connector.connect(
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 544, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "E:\anaconda\envs\nb\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
>     raise ClientConnectorError(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.asmr-200.com:443 ssl:default [getaddrinfo failed]
> ```

还是网络问题，要不就是api服务器抽风

**Comment by YRRLYB** [comment]
问题解决不抽风了

**Comment by YRRLYB** [comment]
前脚刚说完，然后生成音频这一块又出问题了，签名配置怎么改
08-16 19:23:17 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_asmr, lineno=38)
08-16 19:23:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_asmr, lineno=38) running complete
08-16 19:23:17 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_asmr, lineno=38) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\bot\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\bot\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\bot\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\bot\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\bot\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "D:\bot\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot_plugin_asmr\__init__.py", line 184, in _play2
    await play.send(m)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 228, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 181, in send
    return await bot.send_msg(**params)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 147, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "D:\bot\llonebot\nonebot\buding\.venv\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=1200, data=None, message='音乐签名地址未配置', wording='音乐签名地址未配置', echo='572')
DEBUG:aiosqlite:executing <function connect.<locals>.connector at 0x000002770FF865F0>
DEBUG:aiosqlite:operation <function connect.<locals>.connector at 0x000002770FF865F0> completed

**Comment by laiyoi** [comment]
在llob里面
![image](https://github.com/user-attachments/assets/6c253f21-4f6a-42b9-ab9d-3b6e103ef921)

**Comment by laiyoi** [comment]
但是填什么我不知道

**Comment by YRRLYB** [comment]
aa？我等会看看

**Comment by YRRLYB** [comment]
行了，llb和nc的讨论群有那个音频签名地址
